---
efiSystemPartition: "/boot/efi"
efiSystemPartitionSize: "512M"
efiSystemPartitionName: "EFI"

defaultFileSystemType: "btrfs"

btrfsSubvolumes:
  - mountPoint: /
    subvolume: "@"
    mountOptions: "noatime,compress=zstd,space_cache=v2"
  - mountPoint: /home
    subvolume: "@home"
    mountOptions: "noatime,compress=zstd,space_cache=v2"
  - mountPoint: /.snapshots
    subvolume: "@snapshots"
    mountOptions: "noatime,compress=zstd,space_cache=v2"
  - mountPoint: /var/log
    subvolume: "@log"
    mountOptions: "noatime,compress=zstd,space_cache=v2"
  - mountPoint: /var/cache
    subvolume: "@cache"
    mountOptions: "noatime,compress=zstd,space_cache=v2"

userSwapChoices:
  - none
  - small
  - suspend
  - file
