---
defaultGroups:
  - name: users
    must_exist: true
    system: false
  - name: lp
    must_exist: false
    system: true
  - name: video
    must_exist: false
    system: true
  - name: network
    must_exist: false
    system: true
  - name: storage
    must_exist: false
    system: true
  - name: wheel
    must_exist: false
    system: true
  - name: audio
    must_exist: false
    system: true
  - name: input
    must_exist: false
    system: true

autologinGroup: autologin
doAutologin: false
sudoersGroup: wheel
setRootPassword: false
doReusePassword: true

passwordRequirements:
  minLength: 6
  maxLength: -1
  libpwquality:
    - minlen=6

allowWeakPasswords: false
userShell: /bin/zsh
