//! Theming for breadhelp.
//!
//! Like bos-settings, breadhelp owns almost no styling: it loads the
//! ecosystem's shared stylesheet (generated by `bread-theme` from the pywal
//! palette) and layers only the layout rules specific to this app's tab
//! switcher + content shell on top.

use gtk4::CssProvider;
use std::cell::RefCell;

const APP_CSS: &str = "\
.view-content { padding: 24px; }\n\
.view-content > label.title { margin-bottom: 16px; }\n\
/* [Show Keybind] chip: reads as a keycap inline with guide/keybind-viewer text. */\n\
label.keybind-chip { \
  font-family: monospace; \
  font-size: 11px; \
  padding: 2px 6px; \
  border-radius: 6px; \
  background-color: alpha(@on-surface, 0.12); \
}\n\
/* Special modes (ui/modes.rs) — Beginner/Dad bump text and touch targets; \
   Compact tightens padding. Content simplification (content.beginner.md) \
   is a separate, content-level concern — this is visual only. */\n\
.beginner-mode label, .dad-mode label { font-size: 15px; }\n\
.dad-mode label { font-size: 17px; }\n\
.dad-mode button { min-height: 44px; padding: 10px 18px; }\n\
.beginner-mode button { min-height: 36px; }\n\
.compact-mode .view-content { padding: 12px; }\n\
/* ui::tour — mask strips dim everything except the spotlight cutout; the \
   callout is a small floating card near (or, for no-target steps, centered \
   over) the highlighted thing. The shared stylesheet's `window { \
   background-color: @bg }` rule matches every GtkWindow including these — \
   without this override GTK paints that opaque backdrop before the \
   translucent mask box composites onto it, so the alpha never reaches the \
   compositor and the \"dim\" reads as solid black. A class-qualified \
   selector beats the shared rule's bare type selector on specificity \
   regardless of stylesheet load order. */\n\
window.tour-window { background-color: transparent; }\n\
.tour-mask { background-color: rgba(0, 0, 0, 0.65); }\n\
.tour-callout { \
  background-color: @surface; \
  color: @on-surface; \
  border-radius: 12px; \
  padding: 16px 20px; \
}\n\
.tour-callout label.title { font-weight: bold; font-size: 15px; }\n\
/* The one payoff line in the whole tour — the user did the real thing and \
   the compositor proved it — shouldn't read as the same throwaway meta \
   text as the step counter. */\n\
.tour-confirmed { color: @green; font-weight: bold; }\n\
/* Extra top margin (on top of the callout's uniform 12px row gap) marks \
   the \"Show me\" fallback as its own beat, not a continuation of the \
   instructional paragraph above it. */\n\
.tour-hint-row { margin-top: 8px; }\n\
";

thread_local! {
    static APP_PROVIDER: RefCell<Option<CssProvider>> = const { RefCell::new(None) };
}

pub fn load(_display: &gtk4::gdk::Display) {
    bread_theme::gtk::apply_shared();
    APP_PROVIDER.with(|cell| bread_theme::gtk::apply_css(APP_CSS, cell));
}
